project:
  type: book

book:
  title: "R for Economic Research"
  description: "Essential tools for modern economic analysis"
  author: "J. Renato Leripio"
  date: "4/30/2023"
  repo-url: https://github.com/leripio/R4ER
  site-url: "http://book.rleripio.com"
  google-analytics: "G-6T89HT07F5"
  cover-image: "images/cover.jpg"
  chapters:
    - index.qmd
    - part: 'Data science with Tidyverse'
      chapters:
      - ds_tidyverse.qmd
      - ds_googlemob.qmd
    - part: 'Basic time series tools'
      chapters:
      - ds_windowing.qmd
      - ds_seasonality.qmd
      - ds_nominal2real.qmd
      - ds_hpfilter.qmd
    - part: 'Forecasting'
      chapters:
      - fc_abc.qmd
      - fc_comparison.qmd
      - fc_simulation.qmd
    - part: 'Economic modelling'
      chapters:
      - single_equation.qmd
      - multiple_equations.qmd
    - part: 'State-space models'
      chapters:
      - ss_intro.qmd
      - ss_tv_coef.qmd
      - ss_common.qmd
    - references.qmd
  search: true
  twitter-card:
    image: "images/preview.jpg"
  #downloads: [pdf, epub]
  sharing: [twitter, facebook, linkedin]
  sidebar:
    style: docked
    background: light

bibliography: references.bib
    
format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual